version: '3.7'

services:
  central-viewer:
    build:
        context: "."
    environment:
      - API_URL=http://localhost:3000/api
      - GEOSERVER_URL=http://localhost:8082/geoserver/wfs
    ports:
      - 8080:8080
