version: '3.7'

networks:
  backend:
    name: backend
    driver: bridge

services:
  central-viewer:
    build:
        context: "."
    ports:
      - 4200:4200
    environment:
      - CONFIGURATION=production
      - PROXY_CONFIG=src/proxy.conf.json
    networks:
      - backend
