apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-viewer
spec:
  selector:
    matchLabels:
      app: central-viewer
  template:
    spec:
      containers:
      - image: acrsensrnetregistry.azurecr.io/sensrnet/central-viewer:latest
        name: central-viewer
        resources: {}
